### ISSUE TITLE
In included file: unknown type name '__darwin_wint_t'

### ISSUE THREAD

**Issue by Season0518** [FeignClaims/cpp_conan_template#15]
I recently updated my Macos system and clangd stopped working properly

What I tried:
 - brew reinstall gcc
 - reinstall xcode-select

When I tried to modify  `compile_commands.json`, I found that when I downgraded to gcc12 and removed the `-arch arm64` flag, clangd worked fine,

![image](https://github.com/user-attachments/assets/7acbcf75-3086-425e-bf43-e4330ab85258)
corresponding compile_commands.json:
``` json
{
  "directory": "/Users/season/Projects/cpp_xmake",
  "arguments": ["/opt/homebrew/bin/g++-12", "-c", "-std=c++20", "-Idependency/include", "-DLOCAL", "-o", "build/.objs/structure_only/macosx/arm64/release/src/Postgraduate/2018_967_06.cpp.o", "src/Postgraduate/2018_967_06.cpp"],
  "file": "src/Postgraduate/2018_967_06.cpp"
},
```

when I added the `-arch arm64` flag, it didn't work properly.

![image](https://github.com/user-attachments/assets/2595a6e0-e294-451d-a843-4499f0c5e0f0)

corresponding compile_commands.json:
``` json
{
  "directory": "/Users/season/Projects/cpp_xmake",
  "arguments": ["/opt/homebrew/bin/g++-12", "-c", "-std=c++20", "-Idependency/include", "-DLOCAL", "-arch", "arm64", "-isysroot", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-o", "build/.objs/structure_only/macosx/arm64/release/src/Postgraduate/2018_967_06.cpp.o", "src/Postgraduate/2018_967_06.cpp"],
  "file": "src/Postgraduate/2018_967_06.cpp"
},
```

but when I upgraded to gcc13/14, it didn't work properly **with or without**  `-arch arm64` flag.

![image](https://github.com/user-attachments/assets/06cc2459-c9f3-4b13-8af1-ac70e5133e54)

corresponding compile_commands.json:
``` json
{
  "directory": "/Users/season/Projects/cpp_xmake",
  "arguments": ["/opt/homebrew/bin/g++-14", "-c", "-std=c++20", "-Idependency/include", "-DLOCAL", "-o", "build/.objs/structure_only/macosx/arm64/release/src/Postgraduate/2018_967_06.cpp.o", "src/Postgraduate/2018_967_06.cpp"],
  "file": "src/Postgraduate/2018_967_06.cpp"
},
```

How did this problem arise and how should it be solved?

revenant setting:
``` json
    "clangd.arguments": [
        "--query-driver=/opt/homebrew/bin/*",
        "--compile-commands-dir=${workspaceFolder}/.vscode",
        "--enable-config",
        "-j=8",
        "--background-index",
        "--completion-parse=auto",
        "--function-arg-placeholders=false",
        "--header-insertion=never",
        "--pch-storage=memory",
        "--ranking-model=decision_forest",
        "--pretty",
        "-log=verbose"
    ],
```

MacOS version: 15.1.1 (24B91)

SDK:
xcode-select: version 2409
gcc: gcc-13/gcc-12/gcc-14 (Homebrew GCC 13.2.0) 14.2.0/13.2.0/12.4.0
clangd: Homebrew clangd version 19.1.4

**Comment by FeignClaims** [comment]
maybe you could
- `brew uninstall gcc --ignore-dependencies` then `brew install gcc`
- or simply [remove the flag in clangd](https://clangd.llvm.org/config#remove)

**Comment by Season0518** [comment]
This doesn't work

``` bash
season@Mac ~ % brew uninstall gcc --ignore-dependencies
Uninstalling /opt/homebrew/Cellar/gcc/14.2.0_1... (1,914 files, 459.8MB)
season@Mac ~ % brew install gcc
==> Downloading https://formulae.brew.sh/api/formula.jws.json
####################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
####################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gcc/manifests/14.2.0_1
Already downloaded: /Users/season/Library/Caches/Homebrew/downloads/cece94dbe926093c968a24f66b9a0172afe5cc2ef22253029bc591147237045b--gcc-14.2.0_1.bottle_manifest.json
==> Fetching gcc
==> Downloading https://ghcr.io/v2/homebrew/core/gcc/blobs/sha256:96d8bf02f621cfa180cfe6c466fe0aff2cf3f48eab52
Already downloaded: /Users/season/Library/Caches/Homebrew/downloads/3af0c0cf1c9ea5384f04c8820a5321bad19e82b02335cdc4491b0eaa6de05761--gcc--14.2.0_1.arm64_sequoia.bottle.tar.gz
==> Pouring gcc--14.2.0_1.arm64_sequoia.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gcc/14.2.0_1: 1,914 files, 459.8MB
==> Running `brew cleanup gcc`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

After reinstalling gcc:
![image](https://github.com/user-attachments/assets/c5093f75-829c-452d-b7f9-761c12143879)

``` json
{
  "directory": "/Users/season/Projects/cpp_xmake",
  "arguments": ["/opt/homebrew/bin/g++-14", "-c", "-std=c++20", "-Idependency/include", "-DLOCAL", "-arch", "arm64", "-isysroot", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-o", "build/.objs/structure_only/macosx/arm64/release/src/Postgraduate/2018_967_06.cpp.o", "src/Postgraduate/2018_967_06.cpp"],
  "file": "src/Postgraduate/2018_967_06.cpp"
},
```

And we can't just disable this error, like `__float128 is not supported on this target`, because it stops the analysis of subsequent header files.

just like:
![image](https://github.com/user-attachments/assets/bc262392-090a-45b5-a06a-c19f1d929720)

**Comment by FeignClaims** [comment]
> And we can't just disable this error, like __float128 is not supported on this target, because it stops the analysis of subsequent header files.

Oh I referenced the wrong link, the correct link is [here](https://clangd.llvm.org/config#suppress). As far as i know, the config of this template has already disabled the `__float128 is already suppressed` erorr. For external headers, have you add a [`"--compile-commands-dir=${workspaceFolder}"`]() in your vscode clangd settings?
Also, this is not an issue related to this C++ template, plz report it to [clangd/clangd](https://github.com/clangd/clangd/issues).
![image](https://github.com/user-attachments/assets/11410208-5e4b-45a8-b39e-0137c69e0089)

**Comment by Season0518** [comment]
> Also, this is not an issue related to this C++ project template, plz report it to [clangd/clangd](https://github.com/clangd/clangd/issues).

Sorry for the trouble! I will file an issue with the clangd repository.

> have you add a ["--compile-commands-dir=${workspaceFolder}"](https://github.com/FeignClaims/cpp_conan_template/issues/15) in your vscode clangd settings?

Everything seems to be working fine. clangd can recognize the headers correctly. This seems to be a problem with clangd, not the template.

![image](https://github.com/user-attachments/assets/ad60f81a-350b-4e48-9875-d75a5b4ba4f1)

**Comment by FeignClaims** [comment]
> > Also, this is not an issue related to this C++ project template, plz report it to [clangd/clangd](https://github.com/clangd/clangd/issues).
> 
> Sorry for the trouble! I will file an issue with the clangd repository.
> 
> > have you add a ["--compile-commands-dir=${workspaceFolder}"](https://github.com/FeignClaims/cpp_conan_template/issues/15) in your vscode clangd settings?
> 
> Everything seems to be working fine. clangd can recognize the headers correctly. This seems to be a problem with clangd, not the template.
> 
> ![image](https://private-user-images.githubusercontent.com/30144502/392638171-ad60f81a-350b-4e48-9875-d75a5b4ba4f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzQyNDEsIm5iZiI6MTczMzM3Mzk0MSwicGF0aCI6Ii8zMDE0NDUwMi8zOTI2MzgxNzEtYWQ2MGY4MWEtMzUwYi00ZTQ4LTk4NzUtZDc1YTViNGJhNGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA0NDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMjU2YjQ1YjVkYWQ0MGY4NjcxMThhMmY1N2RhM2JkZDBjNmMyNzg0N2Q4ZjdiYWJlNWE2OTljYTAxNmFlNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ru1uY8_3fX_M4RvyGemSfy3FhRHmwZOv3OITDypo1A0)

You could also set a global clangd setting in user folder BTW. See `clangd --help`

**Comment by Season0518** [comment]
Actually, this problem also affects the [[cpp_novice]](https://github.com/FeignClaims/cpp_novice_template)

![image](https://github.com/user-attachments/assets/1674a71f-02e1-443b-bc8e-6177292a5696)

Perhaps we should advise users to be cautious when upgrading or roll back when problems occur

**Comment by FeignClaims** [comment]
> Actually, this problem also affects the [[cpp_novice]](https://github.com/FeignClaims/cpp_novice_template)

Affects, yes. Related, no.

> Oh I referenced the wrong link, the correct link is [here](https://clangd.llvm.org/config#suppress). As far as i know, the config of this template has already disabled the __float128 is already suppressed erorr.

I've given your a solution, and I tested it works well.

![image](https://github.com/user-attachments/assets/e3329cb5-d165-4b90-bed6-340fd114711e)

**Comment by FeignClaims** [comment]
> > Actually, this problem also affects the [[cpp_novice]](https://github.com/FeignClaims/cpp_novice_template)
> 
> Affects, yes. Related, no. This is an issue specific to your environment and software, which goes beyond the scope of this project.
> 
> > Oh I referenced the wrong link, the correct link is [here](https://clangd.llvm.org/config#suppress). As far as i know, the config of this template has already disabled the __float128 is already suppressed erorr.
> 
> I've given your a solution, and I tested it works well at least in my macbook. Don't forget to delete your `build` and `.cache` folder after your reconfiguring `.clangd`.
> 
> ![image](https://private-user-images.githubusercontent.com/62583114/393094575-e3329cb5-d165-4b90-bed6-340fd114711e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTg4ODMsIm5iZiI6MTczMzQ1ODU4MywicGF0aCI6Ii82MjU4MzExNC8zOTMwOTQ1NzUtZTMzMjljYjUtZDE2NS00YjkwLWJlZDYtMzQwZmQxMTQ3MTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA0MTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZTUzMzM2ZGFiZjg1MDAzOWQ5NDlmOTM5YTI2NjZmYmJiNjRkY2ExNWZmNWQwYWQ1ZTQ2ZTRmZjkyNDU5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kK-rq1m8TM1iA1_Tf5TJRiAamcTHujv93B8FEArKOsg)

Forgot to mention, also change `"--query-driver=/opt/homebrew/bin/*"` to `"--query-driver=/opt/homebrew/bin/gcc"`

**Comment by Season0518** [comment]
> Forgot to mention, also change "--query-driver=/opt/homebrew/bin/*" to "--query-driver=/opt/homebrew/bin/gcc-14"

I think If you want to specific driver, you should set this parameter as same as `compile_commands.json`, and correct setting is `--query-driver=/opt/homebrew/bin/aarch64-apple-darwin24-g++-14`

If this is not set, clangd may not parse header files correctly.

Hover the mouse over the header file to confirm that the header file is not correctly identified.

![image](https://github.com/user-attachments/assets/8eca4a65-b683-4d9a-91d6-76e6c9453ce8)


> I've given your a solution, and I tested it works well at least in my macbook. 

It may be a problem with my environment. I tried this operation(suppress error) yesterday and it will stop the analysis of subsequent files.

How to reproduce?

step1: change `--query-driver` to `--query-driver=/opt/homebrew/bin/aarch64-apple-darwin24-g++-14` or `--query-driver=/opt/homebrew/bin/*`

step2: clean cache:

![image](https://github.com/user-attachments/assets/c164fc45-f0cb-4244-a0ca-b0727b97d9cb)

step3: re-generate compile_commands.json

![image](https://github.com/user-attachments/assets/d75c3fa8-e5eb-40ff-b8f7-e9d55a2ad5d0)

![image](https://github.com/user-attachments/assets/fe71cf2a-b57a-44eb-b095-985a63cbead4)

step4: reload clangd or window completely, new error was shown.

![image](https://github.com/user-attachments/assets/61103690-b403-4cb6-acd5-18581bbf8148)

**Comment by FeignClaims** [comment]
> > Forgot to mention, also change "--query-driver=/opt/homebrew/bin/*" to "--query-driver=/opt/homebrew/bin/gcc-14"
> 
> I think If you want to specific driver, you should set this parameter as same as `compile_commands.json`, and correct setting is `--query-driver=/opt/homebrew/bin/aarch64-apple-darwin24-g++-14`

Sorry, I reproduced again and found out this problem occurs when you using homebrew g++-14 on macos with C++ standard higher than 17, which obviously has nothing to do with this project template. Maybe we could report the issue to the correct upstream.

reproduce:

<details>
<summary>CMakeLists.txt</summary>

```cmake
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 20)

cmake_minimum_required(VERSION 3.25)
project(cpp_test LANGUAGES C CXX)

add_executable(test)
target_sources(test
  PRIVATE
  main.cpp
)
```
</details>

<details>
<summary>main.cpp</summary>

```cpp
#include <iostream>

int main() {}
```
</details>

**Comment by FeignClaims** [comment]
closed as this is an upstream issue
